
* dotfiles

dotfiles I use

** Emacs todos

*** Housekeeping

- After the split of main.el, clean up the files

*** More important

- Try corfu
- Try vertico/consult/marginella
- Try project.el
- Download all packages and store as check-in
- Pass ripgrep args to both find file name and find file content, understand how it works
- Only keep the theme I use from doom-themes
- Ask on SE/emacs why gc slower when more packages loaded
- Lower memory usage. Garbage collection is slow for me. Even if my config
  doesn't generate more garbage than more lightweight configs, because so much
  memory is used, it takes time to find the garbage. My guess at least. (BIG)
  - One suggestion was to decrease shell term size.
- Change to emacs built-in search and search-and-replace
- fundamental-mode normal-state keybinds. Add some plain-state
- for dwim find file, support git ls-files, git grep, rg options (for ignoring
  ignore), select if cwd or root

*** Less important

- More than one help window, and don't make them disappear so quickly
- Undo each step in search-and-replace, i.e. migrate to emacs' query-replace
- make counsel-rg fall back to grep if rg isn't found, i.e. on remote
- rg options, e.g. ignore gitignore, only certain file types, fold on file, etc
- Make relative line numebrs correct in vdiff
- More colorful dired, like ll
- vdiff: the problem is that overlays are not being allowed to be partially
  inisivible. But only at top
- vim mark, but name them, cycle through with ivy
- when new buffer, ALWAYS switch to it for consistent behavior
- consider change ctrl to meta

*** Not important at all

- lsp diagnostics
- cleaner magit transient (BIG)
- alt-ret for continuing list also outside org-mode
- cache modeline segments, like doom modeline

*** Wanted, but hard to do

- Box around the cursorline, like VSCode

* "Merge Survival Knife"

** Principles

This tool sets up five different views of the merge conflict according to the figure below.

#+begin_src

         LOCAL
        /  |  \
       /   |   \
      /    |    \
     /     |     \
    /      |      \
BASE       |       MERGED
    \      |      /
     \     |     /
      \    |    /
       \   |   /
        \  |  /
         REMOTE

#+end_src

LOCAL is the version in the target branch, "your changes".
REMOTE is the version in the branch you're merging in, "others' changes".
BASE is the merge base between LOCAL and REMOTE.
MERGED is the merged result.

I use the different diffs the following way:

- BASE <-> LOCAL for understanding what changes I have made since the merge base.
- BASE <-> REMOTE for understanding what changes other people have made since the merge base.
- LOCAL <-> REMOTE if LOCAL and REMOTE have made very similar changes, I use this to understand the difference between them. Useful if you have manually copy-pasted code from the branch to merge from, but also made a few changes on your own.
- REMOTE <-> MERGED for understanding what changes I will "apply" to the branch I'm merging from, if I were to merge my changes to it. For example, if I create a branch based on the main branch, I do a few changes, and main does a few changes, then this diff shows what I would apply to main if I merge to main.
- LOCAL <-> MERGED for understanding what changes remote will "apply" to my branch after I merge.

BASE <-> LOCAL shows your intention. So that diff should look very similar to REMOTE <-> MERGED if you have correctly preserved your intentions after the merge.

Similiarly, BASE <-> REMOTE shows others' intentions, so it should look the same as LOCAL <-> MERGED.

In other words, I use 

- BASE <-> LOCAL
- BASE <-> REMOTE
- LOCAL <-> REMOTE

for understanding the conflict, and

- REMOTE <-> MERGED
- LOCAL <-> MERGED

for reviewing my resolution of the conflict.

** How to use it

The tool is based on [[https://github.com/justbur/emacs-vdiff][vdiff]].

| My key    | Command             | Description                                       |
|-----------+---------------------+---------------------------------------------------|
| =SPC g m= | =msk-mode-enable=   | Start solving the merge conflict the cursor is in |
| =C-c q=   | =msk-mode-disable=  | Save your resolution of the merge conflict        |
| =M-1=     | =msk-base-local=    | Change diff view to BASE-LOCAL                    |
| =M-2=     | =msk-base-remote=   | Change diff view to BASE-REMOTE                   |
| =M-3=     | =msk-local-remote=  | Change diff view to LOCAL-REMOTE                  |
| =M-4=     | =msk-local-merged=  | Change diff view to LOCAL-MERGED                  |
| =M-5=     | =msk-remote-merged= | Change diff view to REMOTE-MERGED                 |
