
* dotfiles

dotfiles I use

** Emacs todos

*** Housekeeping


*** Must have

- Native compilation of packages and my files
- Try corfu
- Try vertico/consult/marginella
- Try project.el
- Download all packages and store as check-in
- Pass ripgrep args to both find file name and find file content, understand how it works
- Only keep the theme I use from doom-themes

*** Nice to have

- Lower memory usage. Garbage collection is slow for me. Even if my config doesn't generate more garbage than more lightweight configs, because so much memory is used, it takes time to find the garbage. My guess at least. (BIG)
- More than one help window, and don't make them disappear so quickly
- Undo each step in search-and-replace, i.e. migrate to emacs' query-replace
- lsp diagnostics
- Make magit use the highlighted file instead of prompting and using the highlighted file as default
- make counsel-rg fall back to grep if rg isn't found, i.e. on remote
- rg options, e.g. ignore gitignore, only certain file types, fold on file, etc
- cleaner magit transient (BIG)
- Merge commit analyzer
  - Check diff between merge base and both parents. Fix by dwim command in magit commit show mode
  - Also check changes in files made by both parents
- Make relative line numebrs correct in vdiff
- Tweak lsp settings so that they don't send unused stuff. Could speed up GC
- More colorful dired, like ll
- for dwim find file, support git ls-files, git grep, rg options (for ignoring ignore), select if cwd or root
- Use window display changed function for super save, etc
- vdiff: the problem is that overlays are not being allowed to be partially inisivible. But only at top
- vim mark, but name them, cycle through with ivy
- when new buffer, ALWAYS switch to it for consistent behavior
- fix auto-save for q (bury-buffer)
- fundamental-mode normal-state keybinds. Add some plain-state
- consider change ctrl to meta

*** Not that important

- alt-ret for continuing list also outside org-mode
- cache modeline segments, like doom modeline

*** Wanted, but hard to do

- Box around the cursorline, like VSCode

* "Merge Survival Knife"

** Principles

This tool sets up five different views of the merge conflict according to the figure below.

#+begin_src

         LOCAL
        /  |  \
       /   |   \
      /    |    \
     /     |     \
    /      |      \
BASE       |       MERGED
    \      |      /
     \     |     /
      \    |    /
       \   |   /
        \  |  /
         REMOTE

#+end_src

LOCAL is the version in the target branch, "your changes".
REMOTE is the version in the branch you're merging in, "others' changes".
BASE is the merge base between LOCAL and REMOTE.
MERGED is the merged result.

I use the different diffs the following way:

- BASE <-> LOCAL for understanding what changes I have made since the merge base.
- BASE <-> REMOTE for understanding what changes other people have made since the merge base.
- LOCAL <-> REMOTE if LOCAL and REMOTE have made very similar changes, I use this to understand the difference between them. Useful if you have manually copy-pasted code from the branch to merge from, but also made a few changes on your own.
- REMOTE <-> MERGED for understanding what changes I will "apply" to the branch I'm merging from, if I were to merge my changes to it. For example, if I create a branch based on the main branch, I do a few changes, and main does a few changes, then this diff shows what I would apply to main if I merge to main.
- LOCAL <-> MERGED for understanding what changes remote will "apply" to my branch after I merge.

BASE <-> LOCAL shows your intention. So that diff should look very similar to REMOTE <-> MERGED if you have correctly preserved your intentions after the merge.

Similiarly, BASE <-> REMOTE shows others' intentions, so it should look the same as LOCAL <-> MERGED.

In other words, I use 

- BASE <-> LOCAL
- BASE <-> REMOTE
- LOCAL <-> REMOTE

for understanding the conflict, and

- REMOTE <-> MERGED
- LOCAL <-> MERGED

for reviewing my resolution of the conflict.

** How to use it

The tool is based on [[https://github.com/justbur/emacs-vdiff][vdiff]].

| My key    | Command             | Description                                       |
|-----------+---------------------+---------------------------------------------------|
| =SPC g m= | =msk-mode-enable=   | Start solving the merge conflict the cursor is in |
| =C-c q=   | =msk-mode-disable=  | Save your resolution of the merge conflict        |
| =M-1=     | =msk-base-local=    | Change diff view to BASE-LOCAL                    |
| =M-2=     | =msk-base-remote=   | Change diff view to BASE-REMOTE                   |
| =M-3=     | =msk-local-remote=  | Change diff view to LOCAL-REMOTE                  |
| =M-4=     | =msk-local-merged=  | Change diff view to LOCAL-MERGED                  |
| =M-5=     | =msk-remote-merged= | Change diff view to REMOTE-MERGED                 |


Warning (bytecomp): reference to free variable ‘server-name’
Warning (bytecomp): reference to free variable ‘evil-normal-state-map’
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘server-done’ is not known to be defined.
Warning (bytecomp): the function ‘server-running-p’ is not known to be defined.
Warning (bytecomp): the function ‘ol-global-set-key’ is not known to be defined.
Warning (bytecomp): the function ‘counsel-find-file’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Error (bytecomp): Symbol’s function definition is void: ol-override-key
Warning (bytecomp): reference to free variable ‘ol-black’
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-visual-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-set-face’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-send-cmd-to-visible-vterm-buffers’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-global-set-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-override-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): ‘beginning-of-buffer’ is for interactive use only; use ‘(goto-char (point-min))’ instead.
Warning (bytecomp): ‘magit-status’ is for interactive use only; use ‘magit-status-setup-buffer’ instead.
Warning (bytecomp): reference to free variable ‘file’
Warning (bytecomp): the function ‘ol-main-branch’ is not known to be defined.
Warning (bytecomp): the function ‘vdiff-buffers’ is not known to be defined.
Warning (bytecomp): the function ‘msk-merge-base-with-main’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-set-face’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-global-set-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-override-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-set-face’ is not known to be defined.
Warning (bytecomp): the function ‘c-toggle-comment-style’ is not known to be defined.
Warning (bytecomp): the function ‘ol-global-set-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-override-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): ‘previous-line’ is for interactive use only; use ‘forward-line’ with negative argument instead.
Warning (bytecomp): the function ‘vterm-send-string’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘ol-black’
Warning (bytecomp): reference to free variable ‘ol-white’
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘vterm-send-string’ is not known to be defined.
Warning (bytecomp): the function ‘vterm’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-set-face’ is not known to be defined.
Error (bytecomp): Cannot open load file: No such file or directory, tiny-lsp-client
Warning (bytecomp): reference to free variable ‘ol-diff-green’
Warning (bytecomp): reference to free variable ‘ol-diff-dark-red’
Warning (bytecomp): reference to free variable ‘ol-diff-dark-orange’
Warning (bytecomp): reference to free variable ‘ol-diff-light-orange’
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-set-face’ is not known to be defined.
Warning (bytecomp): the function ‘ol-copy-face-fg-bg’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘desired-name’
Warning (bytecomp): reference to free variable ‘ol-normal-leader-map’
Warning (bytecomp): the function ‘ol-global-set-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-evil-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-get-buffer-name-from-path’ is not known to be defined.
Warning (bytecomp): the function ‘ol-buffer-name-matches’ is not known to be defined.
Warning (bytecomp): the function ‘ol-override-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-normal-leader-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-define-key’ is not known to be defined.
Warning (bytecomp): the function ‘ol-copy-face-fg-bg’ is not known to be defined.
