
services:
  docker2:
    image: docker2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker2
    init: true
    hostname: docker2
    # userns_mode: keep-id:uid=1000,gid=1000
    volumes:
      ### General
      # System access
      - /:/host_root

      - podman-dir:/home/podman/.local/share/containers
    command:
      sleep 100d
volumes:
  # Needed for 2 reasons:
  # 1. cache inner podman images when outer podman restarts
  # 2. Overlay on overlay not allowed
  podman-dir:
