
;; This theme is originally doom-one-light from https://github.com/doomemacs/themes
;; But I have customized it a bit.
;; But, credits to doomemacs!

(deftheme ol
  "Created 2026-09-12.")

(custom-theme-set-faces
 'ol
 '(pulse-highlight-face ((t (:extend nil :background "#FFFFAA"))))
 '(pulse-highlight-start-face ((((class color) (background dark)) (:background "#AAAA33")) (((class color) (background light)) (:background "#FFFFAA"))))
 '(shortdoc-section ((t nil)))
 '(shortdoc-heading ((t nil)))
 '(corfu--cbar ((t (:inherit (corfu--bar corfu-current)))))
 '(corfu--bar ((t (:foreground "#505050"))))
 '(log-view-commit-body ((t nil)))
 '(log-view-message ((t nil)))
 '(log-view-file ((t nil)))
 '(display-fill-column-indicator-warning-face ((t nil)))
 '(yaml-tab-face ((t nil)))
 '(nxml-glyph ((t nil)))
 '(nxml-hash ((t (:inherit (nxml-name)))))
 '(nxml-markup-declaration-delimiter ((t (:inherit (nxml-delimiter)))))
 '(nxml-prolog-keyword ((t (:inherit (font-lock-keyword-face)))))
 '(nxml-prolog-literal-content ((t (:inherit (nxml-delimited-data)))))
 '(nxml-prolog-literal-delimiter ((t (:inherit (nxml-delimited-data)))))
 '(nxml-attribute-value-delimiter ((t (:inherit (nxml-attribute-value)))))
 '(nxml-attribute-value ((t (:inherit (font-lock-string-face)))))
 '(nxml-namespace-attribute-prefix ((t (:inherit (nxml-attribute-local-name)))))
 '(nxml-namespace-attribute-colon ((t (:inherit (nxml-attribute-colon)))))
 '(nxml-namespace-attribute-xmlns ((t (:inherit (nxml-attribute-prefix)))))
 '(nxml-attribute-local-name ((t (:inherit (font-lock-variable-name-face)))))
 '(nxml-attribute-colon ((t (:inherit (nxml-delimiter)))))
 '(nxml-attribute-prefix ((t (:inherit (nxml-name)))))
 '(nxml-element-local-name ((t (:inherit (font-lock-function-name-face)))))
 '(nxml-element-colon ((t (:inherit (nxml-delimiter)))))
 '(nxml-element-prefix ((t (:inherit (nxml-name)))))
 '(nxml-tag-slash ((t (:inherit (nxml-tag-delimiter)))))
 '(nxml-tag-delimiter ((t (:inherit (nxml-delimiter)))))
 '(nxml-entity-ref-delimiter ((t (:inherit (nxml-ref)))))
 '(nxml-entity-ref-name ((t (:inherit (nxml-ref)))))
 '(nxml-char-ref-delimiter ((t (:inherit (nxml-ref)))))
 '(nxml-char-ref-number ((t (:inherit (nxml-ref)))))
 '(nxml-cdata-section-content ((t (:inherit (nxml-text)))))
 '(nxml-cdata-section-CDATA ((t (:inherit (nxml-name)))))
 '(nxml-cdata-section-delimiter ((t (:inherit (nxml-delimiter)))))
 '(nxml-processing-instruction-content ((t (:inherit (nxml-delimited-data)))))
 '(nxml-processing-instruction-target ((t (:inherit (font-lock-keyword-face)))))
 '(nxml-processing-instruction-delimiter ((t (:inherit (nxml-delimiter)))))
 '(nxml-delimiter ((t (:inherit (nxml-text)))))
 '(nxml-text ((t nil)))
 '(nxml-ref ((t (:inherit (font-lock-constant-face)))))
 '(nxml-name ((t (:inherit (font-lock-builtin-face)))))
 '(nxml-delimited-data ((t (:inherit (font-lock-doc-face)))))
 '(nxml-outline-ellipsis ((t (:weight bold))))
 '(nxml-outline-active-indicator ((t (:box (:line-width (1 . 1) :color nil :style nil) :inherit (nxml-outline-indicator)))))
 '(nxml-outline-indicator ((t nil)))
 '(nxml-heading ((t (:weight bold))))
 '(rng-error ((t (:inherit (font-lock-warning-face)))))
 '(rust-string-interpolation ((t (:inherit (font-lock-string-face) :slant italic))))
 '(rust-builtin-formatting-macro ((t (:inherit (font-lock-builtin-face)))))
 '(rust-ampersand-face ((t (:inherit (default)))))
 '(rust-question-mark ((t (:inherit (font-lock-builtin-face) :weight bold))))
 '(rust-unsafe ((t (:inherit (font-lock-warning-face)))))
 '(table-cell ((t (:inverse-video nil :foreground "gray90" :background "blue1"))))
 '(org-indent ((t (:inherit (org-hide)))))
 '(org-mode-line-clock-overrun ((t (:background "red" :inherit (mode-line)))))
 '(org-mode-line-clock ((t (:inherit (mode-line)))))
 '(org-tag-group ((t (:inherit (org-tag)))))
 '(org-macro ((t (:inherit (org-latex-and-related)))))
 '(org-latex-and-related ((t (:weight bold :foreground "#1b2229"))))
 '(org-agenda-calendar-sexp ((t (:inherit (default)))))
 '(org-agenda-calendar-event ((t (:inherit (default)))))
 '(org-agenda-calendar-daterange ((t (:inherit (default)))))
 '(org-agenda-diary ((t (:inherit (default)))))
 '(org-agenda-current-time ((t (:inherit (org-time-grid)))))
 '(org-time-grid ((t (:foreground "#9ca0a4"))))
 '(org-agenda-filter-regexp ((t (:inherit (mode-line)))))
 '(org-agenda-filter-effort ((t (:inherit (mode-line)))))
 '(org-agenda-filter-category ((t (:inherit (mode-line)))))
 '(org-agenda-filter-tags ((t (:inherit (mode-line)))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 88) (background light)) (:background "#eeeeee")) (((class color) (min-colors 88) (background dark)) (:background "#1C1C1C")) (((class color) (min-colors 16) (background light)) (:background "#eeeeee")) (((class color) (min-colors 16) (background dark)) (:background "#1C1C1C")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-upcoming-distant-deadline ((t (:foreground "#999a9e"))))
 '(org-upcoming-deadline ((t (:foreground "#5e6066"))))
 '(org-imminent-deadline ((t (:inherit (org-warning)))))
 '(org-scheduled-previously ((t (:foreground "#1b2229"))))
 '(org-agenda-dimmed-todo-face ((t (:foreground "#9ca0a4"))))
 '(org-scheduled-today ((t (:foreground "#1c1f24"))))
 '(org-scheduled ((t (:foreground "#383a42"))))
 '(org-agenda-date-weekend ((t (:weight ultra-bold :foreground "#6d306d"))))
 '(org-agenda-clocking ((t (:background "#d4e0f8"))))
 '(org-agenda-date-weekend-today ((t (:inherit (org-agenda-date-today)))))
 '(org-agenda-date-today ((t (:weight ultra-bold :foreground "#d396d3"))))
 '(org-agenda-date ((t (:weight ultra-bold :foreground "#b751b6"))))
 '(org-agenda-structure-filter ((t (:inherit (org-warning org-agenda-structure)))))
 '(org-agenda-structure-secondary ((t (:inherit (org-agenda-structure)))))
 '(org-agenda-structure ((t (:weight ultra-bold :foreground "#383a42"))))
 '(org-clock-overlay ((((class color) (min-colors 88) (background light)) (:foreground "black" :background "LightGray")) (((class color) (min-colors 88) (background dark)) (:foreground "white" :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:foreground "black" :background "gray")) (((class color) (min-colors 16) (background dark)) (:foreground "white" :background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-verse ((t (:inherit (org-block)))))
 '(org-quote ((t (:slant italic :extend t :background "#e7e7e7" :inherit (org-block)))))
 '(org-verbatim ((t (:foreground "#50a14f"))))
 '(org-inline-src-block ((t (:inherit (org-block)))))
 '(org-block-end-line ((t (:inherit (org-block-begin-line)))))
 '(org-block-begin-line ((t (:slant italic :foreground "#383a42" :inherit (org-block)))))
 '(org-block ((t (:extend t :background "#f332f332f332"))))
 '(org-document-info-keyword ((t (:inherit (shadow)))))
 '(org-document-info ((t (:foreground "#a626a4"))))
 '(org-document-title ((t (:weight bold :foreground "#a626a4"))))
 '(org-meta-line ((t (:foreground "#84888b"))))
 '(org-code ((t (:foreground "#da8548" :inherit (org-block)))))
 '(org-formula ((t (:foreground "#0184bc"))))
 '(org-table-header ((t (:foreground "Black" :background "LightGray" :inherit (org-table)))))
 '(org-table-row ((t (:inherit (org-table)))))
 '(org-table ((t (:foreground "#b751b6"))))
 '(org-checkbox-statistics-done ((t (:inherit (org-done)))))
 '(org-checkbox-statistics-todo ((t (:inherit (org-todo)))))
 '(org-checkbox ((t (:inherit (org-todo)))))
 '(org-priority ((t (:foreground "#e45649"))))
 '(org-headline-done ((t (:foreground "#383a42"))))
 '(org-headline-todo ((((class color) (min-colors 16) (background light)) (:foreground "Red4")) (((class color) (min-colors 16) (background dark)) (:foreground "Pink2")) (((class color) (min-colors 8) (background light)) (:weight bold))))
 '(org-agenda-done ((t (:inherit (org-done)))))
 '(org-done ((t (:weight bold :inherit (org-headline-done)))))
 '(org-todo ((t (:weight bold :foreground "#50a14f"))))
 '(org-list-dt ((t (:foreground "#4078f2"))))
 '(org-tag ((t (:weight normal :foreground "#84888b"))))
 '(org-sexp-date ((t (:foreground "#383a42"))))
 '(org-date-selected ((((class color) (min-colors 16) (background light)) (:inverse-video t :foreground "Red1")) (((class color) (min-colors 16) (background dark)) (:inverse-video t :foreground "Pink")) (((class color) (min-colors 8) (background light)) (:inverse-video t :foreground "red")) (((class color) (min-colors 8) (background dark)) (:inverse-video t :foreground "red")) (t (:inverse-video t))))
 '(org-date ((t (:foreground "#986801"))))
 '(org-target ((((class color) (background light)) (:underline (:color foreground-color :style line :position nil))) (((class color) (background dark)) (:underline (:color foreground-color :style line :position nil))) (t (:underline (:color foreground-color :style line :position nil)))))
 '(org-ellipsis ((t (:foreground "#e45649" :background "#fafafa"))))
 '(org-footnote ((t (:foreground "#da8548"))))
 '(org-link ((t (:foreground "#4078f2" :inherit (link)))))
 '(org-cite-key ((t (:underline (:color foreground-color :style line :position nil) :foreground "#44838b"))))
 '(org-cite ((t (:foreground "#4aa8b0"))))
 '(org-archived ((t (:foreground "#84888b"))))
 '(org-warning ((t (:foreground "#986801"))))
 '(org-agenda-column-dateline ((t (:inherit (org-column)))))
 '(org-column-title ((((class color) (min-colors 16) (background light)) (:weight bold :underline (:color foreground-color :style line :position nil) :background "grey90")) (((class color) (min-colors 16) (background dark)) (:weight bold :underline (:color foreground-color :style line :position nil) :background "grey30")) (((class color) (min-colors 8)) (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-column ((((class color) (min-colors 16) (background light)) (:underline nil :strike-through nil :slant normal :weight normal :background "grey90")) (((class color) (min-colors 16) (background dark)) (:underline nil :strike-through nil :slant normal :weight normal :background "grey30")) (((class color) (min-colors 8)) (:underline nil :strike-through nil :slant normal :weight normal :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-property-value ((t (:foreground "#84888b"))))
 '(org-drawer ((t (:foreground "#9ca0a4"))))
 '(org-special-keyword ((t (:foreground "#84888b"))))
 '(org-level-8 ((t (:inherit (outline-8)))))
 '(org-level-7 ((t (:inherit (outline-7)))))
 '(org-level-6 ((t (:inherit (outline-6)))))
 '(org-level-5 ((t (:inherit (outline-5)))))
 '(org-level-4 ((t (:inherit (outline-4)))))
 '(org-level-3 ((t (:inherit (outline-3)))))
 '(org-level-2 ((t (:inherit (outline-2)))))
 '(org-level-1 ((t (:inherit (outline-1)))))
 '(org-dispatcher-highlight ((default (:weight bold)) (((class color) (min-colors 88) (background dark)) (:foreground "gold1" :background "gray20")) (((class color) (min-colors 88) (background light)) (:foreground "DarkBlue" :background "SlateGray1")) (((class color) (min-colors 16) (background dark)) (:foreground "yellow")) (((class color) (min-colors 16) (background light)) (:foreground "blue")) (t (:inverse-video t))))
 '(org-hide ((t (:foreground "#fafafa"))))
 '(org-default ((t (:inherit (variable-pitch)))))
 '(calendar-month-header ((t (:inherit (font-lock-function-name-face)))))
 '(calendar-weekend-header ((t (:inherit (font-lock-comment-face)))))
 '(calendar-weekday-header ((t (:inherit (font-lock-constant-face)))))
 '(holiday ((((class color) (background light)) (:background "pink")) (((class color) (background dark)) (:background "chocolate4")) (t (:inverse-video t))))
 '(diary ((((min-colors 88) (class color) (background light)) (:foreground "red1")) (((class color) (background light)) (:foreground "red")) (((min-colors 88) (class color) (background dark)) (:foreground "yellow1")) (((class color) (background dark)) (:foreground "yellow")) (t (:weight bold))))
 '(calendar-today ((t (:underline (:color foreground-color :style line :position nil)))))
 '(ol-buffer-name-mode-line-face ((t (:weight bold))))
 '(ol-evil-plain-state-mode-mode-line-face ((t (:weight bold :foreground "#4078f2"))))
 '(ol-evil-operator-state-mode-line-face ((t (:weight bold))))
 '(ol-evil-emacs-state-mode-line-face ((t (:weight bold :foreground "#a626a4"))))
 '(ol-evil-visual-state-mode-line-face ((t (:weight bold :foreground "#986801"))))
 '(ol-evil-insert-state-mode-line-face ((t (:weight bold :foreground "#e45649"))))
 '(ol-evil-normal-state-mode-line-face ((t (:weight bold :foreground "#5f8700"))))
 '(vdiff-target-face ((t (:inherit (warning) :inverse-video t))))
 '(vdiff-refine-added ((t (:extend t :background "#9fec9d" :inherit nil))))
 '(vdiff-refine-changed ((t (:extend t :background "#ffd787" :inherit nil))))
 '(vdiff-subtraction-fringe-face ((t (:inherit (vdiff-subtraction-face)))))
 '(vdiff-subtraction-face ((t (:extend t :background "#e45649" :inherit nil))))
 '(vdiff-open-fold-face ((t nil)))
 '(vdiff-closed-fold-face ((t (:foreground "#ffffff" :background "#b751b6" :inherit (region)))))
 '(vdiff-change-face ((t (:extend t :background "#f6eee8" :inherit nil))))
 '(vdiff-addition-face ((t (:extend t :background "#9fec9d" :inherit nil))))
 '(haskell-quasi-quote-face ((t (:inherit (font-lock-string-face)))))
 '(haskell-literate-comment-face ((t (:inherit (font-lock-doc-face)))))
 '(haskell-liquid-haskell-annotation-face ((t (:inherit (haskell-pragma-face)))))
 '(haskell-pragma-face ((t (:inherit (font-lock-preprocessor-face)))))
 '(haskell-operator-face ((t (:inherit (font-lock-variable-name-face)))))
 '(haskell-definition-face ((t (:inherit (font-lock-function-name-face)))))
 '(haskell-constructor-face ((t (:inherit (font-lock-type-face)))))
 '(haskell-type-face ((t (:inherit (font-lock-type-face)))))
 '(haskell-keyword-face ((t (:inherit (font-lock-keyword-face)))))
 '(outline-8 ((t (:weight bold :extend t :foreground "#d8e4fc"))))
 '(outline-7 ((t (:weight bold :extend t :foreground "#d292d1"))))
 '(outline-6 ((t (:weight bold :extend t :foreground "#9fbbf8"))))
 '(outline-5 ((t (:weight bold :extend t :foreground "#bc5cba"))))
 '(outline-4 ((t (:weight bold :extend t :foreground "#6f99f5"))))
 '(outline-3 ((t (:weight bold :extend t :foreground "#b751b6"))))
 '(outline-2 ((t (:weight bold :extend t :foreground "#da8548"))))
 '(outline-1 ((t (:weight bold :extend t :foreground "#e45649"))))
 '(flymake-note-fringe ((t (:inherit (compilation-info)))))
 '(flymake-warning-fringe ((t (:inherit (compilation-warning)))))
 '(flymake-error-fringe ((t (:inherit (compilation-error)))))
 '(flymake-eol-information-face ((t (:slant italic :box nil :inherit (flymake-end-of-line-diagnostics-face)))))
 '(flymake-note-echo-at-eol ((t (:inherit (flymake-end-of-line-diagnostics-face compilation-info)))))
 '(flymake-warning-echo-at-eol ((t (:inherit (flymake-end-of-line-diagnostics-face compilation-warning)))))
 '(flymake-error-echo-at-eol ((t (:inherit (flymake-end-of-line-diagnostics-face compilation-error)))))
 '(flymake-end-of-line-diagnostics-face ((t (:height 0.85))))
 '(flymake-note-echo ((t (:inherit (compilation-info)))))
 '(flymake-warning-echo ((t (:inherit (compilation-warning)))))
 '(flymake-error-echo ((t (:inherit (compilation-error)))))
 '(flymake-note ((t (:underline (:color "#50a14f" :style wave :position nil)))))
 '(flymake-warning ((t (:underline (:color "#da8548" :style wave :position nil)))))
 '(flymake-error ((t (:underline (:color "#e45649" :style wave :position nil)))))
 '(vterm-color-inverse-video ((t (:inherit (default)))))
 '(vterm-color-underline ((t (:inherit (default)))))
 '(vterm-color-bright-white ((t (:inherit (term-color-bright-white)))))
 '(vterm-color-bright-cyan ((t (:inherit (term-color-bright-cyan)))))
 '(vterm-color-bright-magenta ((t (:inherit (term-color-bright-magenta)))))
 '(vterm-color-bright-blue ((t (:inherit (term-color-bright-blue)))))
 '(vterm-color-bright-yellow ((t (:inherit (term-color-bright-yellow)))))
 '(vterm-color-bright-green ((t (:inherit (term-color-bright-green)))))
 '(vterm-color-bright-red ((t (:inherit (term-color-bright-red)))))
 '(vterm-color-bright-black ((t (:inherit (term-color-bright-black)))))
 '(vterm-color-white ((t (:foreground "#1b2229" :background "#54595e"))))
 '(vterm-color-cyan ((t (:foreground "#0184bc" :background "#40a2cc"))))
 '(vterm-color-magenta ((t (:foreground "#a626a4" :background "#bc5cba"))))
 '(vterm-color-blue ((t (:foreground "#4078f2" :background "#6f99f5"))))
 '(vterm-color-yellow ((t (:foreground "#986801" :background "#b18d40"))))
 '(vterm-color-green ((t (:foreground "#50a14f" :background "#7bb87b"))))
 '(vterm-color-red ((t (:foreground "#e45649" :background "#ea8076"))))
 '(vterm-color-black ((t (:foreground "#f0f0f0" :background "#f3f3f3"))))
 '(special-glyphs ((t (:inherit (shadow default)))))
 '(term-color-bright-white ((t (:inherit (ansi-color-bright-white)))))
 '(term-color-bright-cyan ((t (:inherit (ansi-color-bright-cyan)))))
 '(term-color-bright-magenta ((t (:inherit (ansi-color-bright-magenta)))))
 '(term-color-bright-blue ((t (:inherit (ansi-color-bright-blue)))))
 '(term-color-bright-yellow ((t (:inherit (ansi-color-bright-yellow)))))
 '(term-color-bright-green ((t (:inherit (ansi-color-bright-green)))))
 '(term-color-bright-red ((t (:inherit (ansi-color-bright-red)))))
 '(term-color-bright-black ((t (:inherit (ansi-color-bright-black)))))
 '(term-color-white ((t (:foreground "#1b2229" :background "#1b2229"))))
 '(term-color-cyan ((t (:foreground "#0184bc" :background "#0184bc"))))
 '(term-color-magenta ((t (:foreground "#a626a4" :background "#a626a4"))))
 '(term-color-blue ((t (:foreground "#4078f2" :background "#4078f2"))))
 '(term-color-yellow ((t (:foreground "#986801" :background "#986801"))))
 '(term-color-green ((t (:foreground "#50a14f" :background "#50a14f"))))
 '(term-color-red ((t (:foreground "#e45649" :background "#e45649"))))
 '(term-color-black ((t (:foreground "#f0f0f0" :background "#f0f0f0"))))
 '(term-fast-blink ((t (:inherit (ansi-color-fast-blink)))))
 '(term-slow-blink ((t (:inherit (ansi-color-slow-blink)))))
 '(term-underline ((t (:inherit (ansi-color-underline)))))
 '(term-italic ((t (:inherit (ansi-color-italic)))))
 '(term-faint ((t (:inherit (ansi-color-faint)))))
 '(term-bold ((t (:weight bold))))
 '(term ((t (:foreground "#383a42"))))
 '(go-dot-mod-module-semver ((t (:inherit (go-dot-mod-module-version)))))
 '(go-dot-mod-module-version ((t (:inherit (default)))))
 '(go-dot-mod-module-name ((t (:inherit (default)))))
 '(go-coverage-covered ((t (:foreground "#2cd495"))))
 '(go-coverage-10 ((t (:foreground "#14ec9b"))))
 '(go-coverage-9 ((t (:foreground "#20e098"))))
 '(go-coverage-8 ((t (:foreground "#2cd495"))))
 '(go-coverage-7 ((t (:foreground "#38c892"))))
 '(go-coverage-6 ((t (:foreground "#44bc8f"))))
 '(go-coverage-5 ((t (:foreground "#50b08c"))))
 '(go-coverage-4 ((t (:foreground "#5ca489"))))
 '(go-coverage-3 ((t (:foreground "#689886"))))
 '(go-coverage-2 ((t (:foreground "#748c83"))))
 '(go-coverage-1 ((t (:foreground "#808080"))))
 '(go-coverage-0 ((t (:foreground "#c00000"))))
 '(go-coverage-untracked ((t (:foreground "#505050"))))
 '(ffap ((t (:inherit (highlight)))))
 '(xref-match ((t (:weight bold :foreground "#50a14f" :background "#f0f0f0"))))
 '(xref-line-number ((t (:foreground "#4078f2"))))
 '(xref-file-header ((t (:inherit (success)))))
 '(anzu-replace-to ((t (:weight bold :foreground "#50a14f" :background "#f0f0f0"))))
 '(anzu-match-3 ((((class color) (background light)) (:foreground "black" :background "yellow")) (((class color) (background dark)) (:foreground "black" :background "aquamarine")) (t (:inverse-video t))))
 '(anzu-match-2 ((((class color) (background light)) (:foreground "black" :background "springgreen")) (((class color) (background dark)) (:foreground "black" :background "yellow")) (t (:inverse-video t))))
 '(anzu-match-1 ((((class color) (background light)) (:foreground "black" :background "aquamarine")) (((class color) (background dark)) (:foreground "black" :background "limegreen")) (t (:inverse-video t))))
 '(anzu-replace-highlight ((t (:weight bold :strike-through t :foreground "#e45649" :background "#f0f0f0"))))
 '(anzu-mode-line-no-match ((t (:inherit (anzu-mode-line)))))
 '(anzu-mode-line ((t (:weight bold :foreground "magenta"))))
 '(dockerfile-image-alias ((t (:inherit (font-lock-constant-face bold)))))
 '(dockerfile-image-name ((t (:inherit (font-lock-type-face bold)))))
 '(sh-escaped-newline ((t (:inherit (font-lock-string-face)))))
 '(sh-quoted-exec ((t (:inherit (font-lock-preprocessor-face)))))
 '(sh-heredoc ((t (:weight normal :inherit (font-lock-string-face)))))
 '(treesit-explorer-field-name ((t nil)))
 '(treesit-explorer-anonymous-node ((t (:inherit (shadow)))))
 '(corfu-deprecated ((t (:strike-through t :inherit (shadow)))))
 '(corfu-annotations ((t (:inherit (completions-annotations)))))
 '(corfu-border ((((class color) (min-colors 88) (background dark)) (:background "#323232")) (((class color) (min-colors 88) (background light)) (:background "#d7d7d7")) (t (:background "gray"))))
 '(corfu-bar ((((class color) (min-colors 88) (background dark)) (:background "#a8a8a8")) (((class color) (min-colors 88) (background light)) (:background "#505050")) (t (:background "black"))))
 '(corfu-current ((t (:extend t :inherit (ol-selection-face fixed-pitch)))))
 '(corfu-default ((t (:inherit (ol-candidate-face fixed-pitch)))))
 '(ol-remote-buffer-name-face ((default (:foreground "#110099"))))
 '(ol-vterm-buffer-name-face ((default (:inherit 'font-lock-type-face :weight bold))))
 '(ol-dired-buffer-name-face ((default (:inherit 'font-lock-function-name-face :weight bold))))
 '(grep-heading ((t (:weight bold :foreground "#000000" :background "#dddddd" :inherit (compilation-info)))))
 '(compilation-column-number ((t (:inherit (font-lock-comment-face)))))
 '(compilation-line-number ((t (:underline nil :inherit (font-lock-string-face)))))
 '(compilation-mode-line-exit ((t (:inherit (compilation-info)))))
 '(compilation-mode-line-run ((t (:inherit (compilation-warning)))))
 '(compilation-mode-line-fail ((t (:inherit (compilation-error)))))
 '(compilation-info ((t (:inherit (success)))))
 '(compilation-warning ((t (:slant italic :inherit (warning)))))
 '(compilation-error ((t (:weight bold :inherit (error)))))
 '(delete-selection-replacement ((t (:inherit (highlight)))))
 '(icomplete-vertical-unselected-prefix-indicator-face ((t (:foreground "gray" :weight normal :inherit (font-lock-keyword-face)))))
 '(icomplete-vertical-selected-prefix-indicator-face ((t (:foreground "slate blue" :weight bold :inherit (font-lock-keyword-face)))))
 '(icomplete-section ((t (:slant italic :inherit (shadow)))))
 '(icomplete-selected-match ((t (:inherit (ol-selection-face)))))
 '(icomplete-first-match ((t (:weight bold))))
 '(c-annotation-face ((default (:inherit (font-lock-constant-face)))))
 '(ol-selection-face ((default (:background "#d7e4e8" :weight bold :extend t))))
 '(ol-match-face ((default (:background unspecified :foreground "#4078f2" :weight bold))))
 '(ol-candidate-face ((default (:background "#ffffff" :foreground "#000000" :weight normal))))
 '(git-rebase-comment-heading ((t (:inherit (font-lock-keyword-face)))))
 '(git-rebase-comment-hash ((t (:weight bold :inherit (git-rebase-hash)))))
 '(git-rebase-killed-action ((t (:strike-through t :inherit (font-lock-comment-face)))))
 '(git-rebase-action ((t (:inherit (font-lock-keyword-face)))))
 '(git-rebase-description ((t nil)))
 '(git-rebase-label ((t (:inherit (magit-refname)))))
 '(git-rebase-hash ((t (:inherit (magit-hash)))))
 '(ediff-odd-diff-Ancestor ((((class color) (min-colors 88)) (:extend t :background "gray40")) (((class color) (min-colors 16)) (:extend t :background "gray40" :foreground "cyan3")) (((class color)) (:extend t :weight bold :background "black" :foreground "green3")) (t (:extend t :stipple "gray1" :slant italic))))
 '(ediff-odd-diff-C ((t (:inherit (ediff-odd-diff-A)))))
 '(ediff-odd-diff-B ((t (:inherit (ediff-odd-diff-A)))))
 '(ediff-odd-diff-A ((t (:inherit (ediff-even-diff-A)))))
 '(ediff-even-diff-Ancestor ((((type pc)) (:extend t :background "light grey" :foreground "cyan3")) (((class color) (min-colors 88) (background light)) (:extend t :background "Grey" :distant-foreground "Black")) (((class color) (min-colors 88) (background dark)) (:extend t :background "dim grey" :distant-foreground "White")) (((class color) (min-colors 16)) (:extend t :background "Grey" :foreground "White")) (((class color)) (:extend t :weight bold :background "light grey" :foreground "cyan3")) (t (:extend t :stipple "stipple" :slant italic))))
 '(ediff-even-diff-C ((t (:inherit (ediff-even-diff-A)))))
 '(ediff-even-diff-B ((t (:inherit (ediff-even-diff-A)))))
 '(ediff-even-diff-A ((t (:inherit (hl-line)))))
 '(ediff-fine-diff-Ancestor ((((class color) (min-colors 88) (background light)) (:background "#00c5c0")) (((class color) (min-colors 88) (background dark)) (:background "#009591")) (((class color) (min-colors 16) (background light)) (:background "#00c5c0")) (((class color) (min-colors 16) (background dark)) (:background "#009591")) (((class color)) (:background "green" :foreground "red3")) (t (:stipple "gray3" :underline (:color foreground-color :style line :position nil)))))
 '(ediff-fine-diff-C ((t (:inherit (ediff-fine-diff-A)))))
 '(ediff-fine-diff-B ((t (:inherit (diff-refine-added)))))
 '(ediff-fine-diff-A ((t (:inherit (diff-refine-removed)))))
 '(ediff-current-diff-Ancestor ((t (:extend t :foreground "#4db5bd" :background "#dbf0f1"))))
 '(ediff-current-diff-C ((t (:extend t :foreground "#4078f2" :background "#d8e4fc"))))
 '(ediff-current-diff-B ((t (:extend t :foreground "#50a14f" :background "#dcecdb"))))
 '(ediff-current-diff-A ((t (:extend t :foreground "#e45649" :background "#f9ddda"))))
 '(magit-blame-date ((t (:foreground "#e45649"))))
 '(magit-blame-name ((t nil)))
 '(magit-blame-hash ((t (:foreground "#0184bc"))))
 '(magit-blame-summary ((t nil)))
 '(magit-blame-heading ((t (:extend t :foreground "#da8548" :background "#f0f0f0"))))
 '(magit-blame-dimmed ((t (:slant normal :weight normal :inherit (magit-dimmed)))))
 '(magit-blame-margin ((t (:weight normal :slant normal :background "#e4e4e4" :inherit (magit-blame-highlight)))))
 '(magit-blame-highlight ((((class color) (background light)) (:foreground "black" :background "grey80" :extend t)) (((class color) (background dark)) (:foreground "white" :background "grey25" :extend t))))
 '(magit-reflog-other ((t (:foreground "#0184bc"))))
 '(magit-reflog-remote ((t (:foreground "#0184bc"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#50a14f"))))
 '(magit-reflog-rebase ((t (:foreground "#a626a4"))))
 '(magit-reflog-reset ((t (:inherit (error)))))
 '(magit-reflog-checkout ((t (:foreground "#4078f2"))))
 '(magit-reflog-merge ((t (:foreground "#50a14f"))))
 '(magit-reflog-amend ((t (:foreground "#a626a4"))))
 '(magit-reflog-commit ((t (:foreground "#50a14f"))))
 '(magit-bisect-bad ((t (:foreground "#e45649"))))
 '(magit-bisect-skip ((t (:foreground "#da8548"))))
 '(magit-bisect-good ((t (:foreground "#50a14f"))))
 '(magit-sequence-exec ((t (:inherit (magit-hash)))))
 '(magit-sequence-onto ((t (:inherit (magit-sequence-done)))))
 '(magit-sequence-done ((t (:inherit (magit-hash)))))
 '(magit-sequence-drop ((t (:foreground "#e45649"))))
 '(magit-sequence-head ((t (:foreground "#4078f2"))))
 '(magit-sequence-part ((t (:foreground "#da8548"))))
 '(magit-sequence-stop ((t (:foreground "#50a14f"))))
 '(magit-sequence-pick ((t (:inherit (default)))))
 '(bookmark-face ((t (:extend t :background "#e7edf9"))))
 '(bookmark-menu-bookmark ((t (:weight bold))))
 '(magit-filename ((t (:foreground "#b751b6"))))
 '(magit-cherry-equivalent ((t (:foreground "#b751b6"))))
 '(magit-cherry-unmatched ((t (:foreground "#0184bc"))))
 '(magit-signature-error ((t (:inherit (error)))))
 '(magit-signature-revoked ((t (:foreground "#a626a4"))))
 '(magit-signature-expired-key ((t (:inherit (magit-signature-expired)))))
 '(magit-signature-expired ((t (:foreground "#da8548"))))
 '(magit-signature-untrusted ((t (:foreground "#986801"))))
 '(magit-signature-bad ((t (:inherit (error)))))
 '(magit-signature-good ((t (:inherit (success)))))
 '(magit-keyword-squash ((t (:inherit (font-lock-warning-face)))))
 '(magit-keyword ((t (:inherit (font-lock-string-face)))))
 '(magit-refname-pullreq ((t (:inherit (magit-refname)))))
 '(magit-refname-wip ((t (:inherit (magit-refname)))))
 '(magit-refname-stash ((t (:inherit (magit-refname)))))
 '(magit-refname ((t (:foreground "#9ca0a4"))))
 '(magit-head ((((class color) (background light)) (:inherit (magit-branch-local))) (((class color) (background dark)) (:inherit (magit-branch-local)))))
 '(magit-branch-warning ((t (:inherit (warning)))))
 '(magit-branch-upstream ((t (:slant italic))))
 '(magit-branch-current ((t (:foreground "#4078f2"))))
 '(magit-branch-local ((t (:foreground "#0184bc"))))
 '(magit-branch-remote-head ((t (:box (:line-width (1 . 1) :color nil :style nil) :inherit (magit-branch-remote)))))
 '(magit-branch-remote ((t (:foreground "#50a14f"))))
 '(magit-tag ((t (:foreground "#986801"))))
 '(magit-hash ((t (:foreground "#9ca0a4"))))
 '(magit-dimmed ((t (:foreground "#c6c7c7"))))
 '(magit-header-line-key ((t (:inherit (font-lock-builtin-face)))))
 '(magit-header-line ((t (:weight bold :box (:line-width (3 . 3) :color "#a0bcf8" :style nil) :foreground "#1b2229" :background "#a0bcf8"))))
 '(epa-field-body ((default (:slant italic)) (((class color) (background dark)) (:foreground "turquoise"))))
 '(epa-field-name ((default (:weight bold)) (((class color) (background dark)) (:foreground "PaleTurquoise"))))
 '(epa-mark ((default (:weight bold)) (((class color) (background dark)) (:foreground "orange")) (((class color) (background light)) (:foreground "red"))))
 '(epa-string ((((class color) (background dark)) (:foreground "lightyellow")) (((class color) (background light)) (:foreground "blue4"))))
 '(epa-validity-disabled ((t (:inverse-video t :slant italic))))
 '(epa-validity-low ((t (:slant italic))))
 '(epa-validity-medium ((default (:slant italic)) (((class color) (background dark)) (:foreground "PaleTurquoise"))))
 '(epa-validity-high ((default (:weight bold)) (((class color) (background dark)) (:foreground "PaleTurquoise"))))
 '(magit-header-line-log-select ((t (:inherit (bold)))))
 '(magit-log-date ((t (:foreground "#da8548"))))
 '(magit-log-author ((t (:foreground "#da8548"))))
 '(magit-log-graph ((t (:foreground "#9ca0a4"))))
 '(magit-diff-whitespace-warning ((t (:inherit (trailing-whitespace)))))
 '(magit-diff-hunk-region ((t (:extend t :inherit (bold)))))
 '(magit-diff-lines-boundary ((t (:extend t :background "#ee0000" :inherit (magit-diff-lines-heading)))))
 '(magit-diffstat-added ((t (:foreground "#50a14f"))))
 '(magit-diffstat-removed ((t (:foreground "#e45649"))))
 '(magit-diff-their-indicator ((t (:inherit (magit-diff-added-indicator)))))
 '(magit-diff-base-indicator ((((class color) (background light)) (:foreground "#aaaa11")) (((class color) (background dark)) (:foreground "#ffffcc"))))
 '(magit-diff-our-indicator ((t (:inherit (magit-diff-removed-indicator)))))
 '(magit-diff-added-indicator ((((class color) (background light)) (:foreground "#22aa22")) (((class color) (background dark)) (:foreground "#cceecc"))))
 '(magit-diff-removed-indicator ((((class color) (background light)) (:foreground "#aa2222")) (((class color) (background dark)) (:foreground "#eecccc"))))
 '(magit-diff-their-highlight ((t (:background "#f5d9d6" :inherit (magit-diff-added-highlight)))))
 '(magit-diff-base-highlight ((t (:weight bold :extend t :foreground "#da8548" :background "#ffd787"))))
 '(magit-diff-our-highlight ((t (:background "#9fec9d" :inherit (magit-diff-removed-highlight)))))
 '(magit-diff-added-highlight ((t (:weight normal :extend t :foreground "#50a14f" :background "#d8e8d7"))))
 '(magit-diff-removed-highlight ((t (:weight normal :extend t :foreground "#e45649" :background "#f5d9d6"))))
 '(magit-diff-context-highlight ((t (:extend t :foreground "#383a42" :background "#ffffff"))))
 '(magit-diff-their ((t (:background "#f5d9d6" :inherit (magit-diff-added)))))
 '(magit-diff-base ((t (:extend t :foreground "#ae6a39" :background "#ffd787"))))
 '(magit-diff-our ((t (:background "#9fec9d" :inherit (magit-diff-removed)))))
 '(magit-diff-added ((t (:extend t :foreground "#40803f" :background "#e9f1e8"))))
 '(magit-diff-removed ((t (:extend t :foreground "#b6443a" :background "#f7e9e8"))))
 '(magit-diff-context ((t (:extend t :foreground "#212227" :background "#ffffff"))))
 '(magit-diff-their-heading ((((class color) (background light)) (:foreground "#ddffdd" :background "#22aa22" :extend t)) (((class color) (background dark)) (:foreground "#335533" :background "#ddffdd" :extend t))))
 '(magit-diff-base-heading ((((class color) (background light)) (:foreground "#ffffcc" :background "#aaaa11" :extend t)) (((class color) (background dark)) (:foreground "#555522" :background "#ffffcc" :extend t))))
 '(magit-diff-our-heading ((((class color) (background light)) (:foreground "#ffdddd" :background "#aa2222" :extend t)) (((class color) (background dark)) (:foreground "#553333" :background "#ffdddd" :extend t))))
 '(magit-diff-lines-heading ((t (:extend t :foreground "#986801" :background "#e45649"))))
 '(magit-diff-revision-summary-highlight ((t (:inherit (magit-diff-hunk-heading-highlight)))))
 '(magit-diff-revision-summary ((t (:inherit (magit-diff-hunk-heading)))))
 '(magit-diff-conflict-heading-highlight ((t (:inherit (magit-diff-hunk-heading-highlight)))))
 '(magit-diff-conflict-heading ((t (:inherit (magit-diff-hunk-heading)))))
 '(magit-diff-hunk-heading-selection ((((class color) (background light)) (:foreground "salmon4" :inherit (magit-diff-hunk-heading-highlight) :extend t)) (((class color) (background dark)) (:foreground "LightSalmon3" :inherit (magit-diff-hunk-heading-highlight) :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:weight bold :extend t :foreground "#ffffff" :background "#b751b6"))))
 '(magit-diff-hunk-heading ((t (:extend t :foreground "#ffffff" :background "#e5c7e5"))))
 '(magit-diff-file-heading-selection ((t (:background "#ffffff"))))
 '(magit-diff-file-heading-highlight ((t (:inherit (magit-section-highlight) :extend t))))
 '(magit-diff-file-heading ((t (:weight bold :extend t :foreground "#383a42"))))
 '(smerge-refine-shadow-cursor ((t (:box (:line-width (-1 . -1) :color nil :style nil)))))
 '(smerge-refined-added ((t (:inverse-video t :inherit (diff-added)))))
 '(smerge-refined-removed ((t (:inverse-video t :inherit (diff-removed)))))
 '(smerge-refined-changed ((t nil)))
 '(smerge-markers ((t (:weight bold :extend t :foreground "#fafafa" :background "#9ca0a4"))))
 '(smerge-base ((t (:weight normal :extend t :foreground "#000000" :background "#ffd787"))))
 '(smerge-lower ((t (:weight normal :extend t :foreground "#000000" :background "#f5d9d6"))))
 '(smerge-upper ((t (:weight normal :extend t :foreground "#000000" :background "#9fec9d"))))
 '(git-commit-comment-action ((t (:inherit (bold)))))
 '(git-commit-comment-file ((t (:foreground "#b751b6"))))
 '(git-commit-comment-button ((t (:underline (:color foreground-color :style line :position nil) :inherit (git-commit-comment-heading)))))
 '(git-commit-comment-heading ((t (:foreground "#e45649"))))
 '(git-commit-comment-detached ((t (:foreground "#da8548"))))
 '(git-commit-comment-branch-remote ((t (:foreground "#50a14f"))))
 '(git-commit-comment-branch-local ((t (:foreground "#a626a4"))))
 '(git-commit-trailer-value ((t (:slant italic :foreground "#84888b"))))
 '(git-commit-trailer-token ((t (:weight bold :slant italic :foreground "#84888b"))))
 '(git-commit-keyword ((t (:slant italic :foreground "#0184bc"))))
 '(git-commit-nonempty-second-line ((t (:inherit (git-commit-overlong-summary)))))
 '(git-commit-overlong-summary ((t (:weight bold :slant italic :background "#f0f0f0" :inherit (error)))))
 '(git-commit-summary ((t (:foreground "#50a14f"))))
 '(log-edit-unknown-header ((t (:inherit (font-lock-comment-face)))))
 '(log-edit-header ((t (:inherit (font-lock-keyword-face)))))
 '(log-edit-headers-separator ((t (:extend t :inverse-video t :height 0.1))))
 '(log-edit-summary ((t (:inherit (font-lock-function-name-face)))))
 '(change-log-acknowledgment ((t (:inherit (font-lock-comment-face)))))
 '(change-log-function ((t (:inherit (font-lock-variable-name-face)))))
 '(change-log-conditionals ((t (:inherit (font-lock-variable-name-face)))))
 '(change-log-list ((t (:inherit (font-lock-keyword-face)))))
 '(change-log-file ((t (:inherit (font-lock-function-name-face)))))
 '(change-log-email ((t (:inherit (font-lock-variable-name-face)))))
 '(change-log-name ((t (:inherit (font-lock-constant-face)))))
 '(change-log-date ((t (:inherit (font-lock-string-face)))))
 '(magit-mode-line-process-error ((t (:inherit (error)))))
 '(magit-mode-line-process ((t (:inherit (mode-line-emphasis)))))
 '(magit-process-ng ((t (:inherit (error)))))
 '(magit-process-ok ((t (:inherit (success)))))
 '(shell-highlight-undef-alias-face ((t (:inherit (font-lock-variable-name-face)))))
 '(shell-highlight-undef-undefined-face ((t (:inherit (font-lock-warning-face)))))
 '(shell-highlight-undef-defined-face ((t (:inherit (font-lock-function-name-face)))))
 '(comint-highlight-prompt ((t (:inherit (minibuffer-prompt)))))
 '(comint-highlight-input ((t (:weight bold))))
 '(ansi-color-bright-white ((t (:foreground "#1b2229" :background "#1b2229"))))
 '(ansi-color-bright-cyan ((t (:foreground "#2796c6" :background "#2796c6"))))
 '(ansi-color-bright-magenta ((t (:foreground "#b346b1" :background "#b346b1"))))
 '(ansi-color-bright-blue ((t (:foreground "#5c8cf3" :background "#5c8cf3"))))
 '(ansi-color-bright-yellow ((t (:foreground "#a77e27" :background "#a77e27"))))
 '(ansi-color-bright-green ((t (:foreground "#6aaf69" :background "#6aaf69"))))
 '(ansi-color-bright-red ((t (:foreground "#e86f64" :background "#e86f64"))))
 '(ansi-color-bright-black ((t (:foreground "#9ca0a4" :background "#9ca0a4"))))
 '(ansi-color-white ((t (:foreground "#383a42" :background "#383a42"))))
 '(ansi-color-cyan ((t (:foreground "#0184bc" :background "#0184bc"))))
 '(ansi-color-magenta ((t (:foreground "#a626a4" :background "#a626a4"))))
 '(ansi-color-blue ((t (:foreground "#4078f2" :background "#4078f2"))))
 '(ansi-color-yellow ((t (:foreground "#986801" :background "#986801"))))
 '(ansi-color-green ((t (:foreground "#50a14f" :background "#50a14f"))))
 '(ansi-color-red ((t (:foreground "#e45649" :background "#e45649"))))
 '(ansi-color-black ((t (:foreground "#fafafa" :background "#fafafa"))))
 '(ansi-color-inverse ((t (:inverse-video t))))
 '(ansi-color-fast-blink ((t (:box (:line-width (1 . -1) :color nil :style nil)))))
 '(ansi-color-slow-blink ((t (:box (:line-width (1 . -1) :color nil :style nil)))))
 '(ansi-color-underline ((t (:inherit (underline)))))
 '(ansi-color-italic ((t (:inherit (italic)))))
 '(ansi-color-faint ((t (:weight light))))
 '(ansi-color-bold ((t (:inherit (bold)))))
 '(browse-url-button ((t (:inherit (link)))))
 '(which-func ((t (:foreground "#4078f2"))))
 '(diff-refine-added ((t (:inverse-video t :inherit (diff-added)))))
 '(diff-refine-removed ((t (:inverse-video t :inherit (diff-removed)))))
 '(diff-refine-changed ((t (:inverse-video t :inherit (diff-changed)))))
 '(diff-error ((((class color)) (:weight bold :background "black" :foreground "red")) (t (:weight bold))))
 '(diff-nonexistent ((t (:inherit (diff-file-header)))))
 '(diff-context ((t (:extend t :foreground "#4f5158"))))
 '(diff-function ((t (:inherit (diff-header)))))
 '(diff-indicator-changed ((t (:foreground "#da8548"))))
 '(diff-indicator-added ((t (:foreground "#50a14f"))))
 '(diff-indicator-removed ((t (:foreground "#e45649"))))
 '(diff-changed ((t (:foreground "#b751b6"))))
 '(diff-changed-unspecified ((default (:inherit (diff-changed))) (((class color) (min-colors 88) (background light)) (:extend t :background "#ffffaa")) (((class color) (min-colors 88) (background dark)) (:extend t :background "#888833")) (((class color)) (:extend t :foreground "yellow"))))
 '(diff-added ((t (:foreground "#50a14f" :inherit (hl-line)))))
 '(diff-removed ((t (:extend t :foreground "#e45649" :background "#c6c7c7"))))
 '(diff-hunk-header ((t (:foreground "#b751b6"))))
 '(diff-index ((t (:inherit (diff-file-header)))))
 '(diff-file-header ((t (:extend t :foreground "#4078f2"))))
 '(diff-header ((t (:extend t :foreground "#0184bc"))))
 '(vc-git-log-edit-summary-max-warning ((t (:inherit (error)))))
 '(vc-git-log-edit-summary-target-warning ((t (:inherit (warning)))))
 '(Info-quoted ((t (:inherit (fixed-pitch-serif)))))
 '(info-index-match ((t (:inherit (match)))))
 '(info-header-node ((t (:inherit (info-node)))))
 '(info-header-xref ((t (:inherit (info-xref)))))
 '(info-xref-visited ((t (:inherit (link-visited info-xref)))))
 '(info-xref ((t (:inherit (link)))))
 '(info-menu-star ((((class color)) (:foreground "red1")) (t (:underline (:color foreground-color :style line :position nil)))))
 '(info-menu-header ((((type tty pc)) (:weight bold :underline (:color foreground-color :style line :position nil))) (t (:weight bold :inherit (variable-pitch)))))
 '(info-title-4 ((((type tty pc) (class color)) (:weight bold)) (t (:inherit (variable-pitch) :weight bold))))
 '(info-title-3 ((((type tty pc) (class color)) (:weight bold)) (t (:inherit (info-title-4) :height 1.2))))
 '(info-title-2 ((((type tty pc) (class color)) (:weight bold :foreground "lightblue")) (t (:inherit (info-title-3) :height 1.2))))
 '(info-title-1 ((((type tty pc) (class color) (background light)) (:weight bold :foreground "green")) (((type tty pc) (class color) (background dark)) (:weight bold :foreground "yellow")) (t (:inherit (info-title-2) :height 1.2))))
 '(info-node ((((class color) (background light)) (:slant italic :weight bold :foreground "brown")) (((class color) (background dark)) (:slant italic :weight bold :foreground "white")) (t (:slant italic :weight bold))))
 '(magit-left-margin ((t (:inherit (default)))))
 '(magit-section-child-count ((t nil)))
 '(magit-section-heading-selection ((t (:weight bold :extend t :foreground "#da8548" :background "#ffffff"))))
 '(magit-section-secondary-heading ((t (:weight bold :extend t :foreground "#b751b6" :background "#ee0000"))))
 '(magit-section-heading ((t (:weight bold :extend t :foreground "#4078f2"))))
 '(magit-section-highlight ((t (:extend t :inherit (hl-line)))))
 '(transient-mismatched-key ((t (:box (:line-width (-1 . -1) :color "magenta" :style nil)))))
 '(transient-nonstandard-key ((t (:box (:line-width (-1 . -1) :color "cyan" :style nil)))))
 '(transient-unreachable-key ((t (:weight normal :inherit (shadow transient-key)))))
 '(transient-key-exit ((((class color) (background light)) (:foreground "#aa2222" :inherit (transient-key))) (((class color) (background dark)) (:foreground "#ffdddd" :inherit (transient-key)))))
 '(transient-key-stack ((((class color) (background light)) (:foreground "#dd4488" :inherit (transient-key))) (((class color) (background dark)) (:foreground "#ff6699" :inherit (transient-key)))))
 '(transient-key-recurse ((((class color) (background light)) (:foreground "#2266ff" :inherit (transient-key))) (((class color) (background dark)) (:foreground "#2299ff" :inherit (transient-key)))))
 '(transient-key-return ((((class color) (background light)) (:foreground "#aaaa11" :inherit (transient-key))) (((class color) (background dark)) (:foreground "#ffffcc" :inherit (transient-key)))))
 '(transient-key-noop ((((class color) (background light)) (:foreground "grey80" :inherit (transient-key))) (((class color) (background dark)) (:foreground "grey30" :inherit (transient-key)))))
 '(transient-key-stay ((((class color) (background light)) (:foreground "#22aa22" :inherit (transient-key))) (((class color) (background dark)) (:foreground "#ddffdd" :inherit (transient-key)))))
 '(transient-key ((t (:inherit (font-lock-builtin-face)))))
 '(transient-delimiter ((t (:inherit (shadow)))))
 '(transient-higher-level ((t (:box (:line-width (-1 . -1) :color "grey60" :style nil)))))
 '(transient-disabled-suffix ((t (:weight bold :foreground "black" :background "red"))))
 '(transient-enabled-suffix ((t (:weight bold :foreground "black" :background "green"))))
 '(transient-active-infix ((t (:inherit (highlight)))))
 '(transient-inapt-suffix ((t (:slant italic :inherit (shadow)))))
 '(transient-unreachable ((t (:inherit (shadow)))))
 '(transient-inactive-value ((t (:inherit (shadow)))))
 '(transient-value ((t (:weight bold :inherit (font-lock-string-face)))))
 '(transient-inapt-argument ((t (:weight bold :inherit (shadow)))))
 '(transient-inactive-argument ((t (:inherit (shadow)))))
 '(transient-argument ((t (:weight bold :inherit (font-lock-string-face)))))
 '(transient-heading ((t (:inherit (font-lock-keyword-face)))))
 '(llama-deleted-argument ((((supports :box t)) (:box (:line-width (-1 . -1) :color "red" :style nil))) (((supports :underline t)) (:underline (:color "red" :style line :position nil))) (t (:inherit (font-lock-warning-face)))))
 '(llama-optional-argument ((t (:inherit (font-lock-type-face)))))
 '(llama-mandatory-argument ((t (:inherit (font-lock-variable-use-face)))))
 '(llama-llama-macro ((t (:inherit (font-lock-keyword-face)))))
 '(llama-\#\#-macro ((t (:inherit (font-lock-function-call-face)))))
 '(hl-line-nonselected ((t (:extend t :inherit (hl-line)))))
 '(hl-line ((t (:extend t :background "#eeeeee"))))
 '(dired-ignored ((t (:foreground "#9ca0a4"))))
 '(dired-special ((t (:inherit (font-lock-variable-name-face)))))
 '(dired-broken-symlink ((((class color)) (:weight bold :background "red1" :foreground "yellow1")) (t (:underline (:color foreground-color :style line :position nil) :slant italic :weight bold))))
 '(dired-symlink ((t (:weight bold :foreground "#0184bc"))))
 '(dired-directory ((t (:foreground "#a626a4"))))
 '(dired-set-id ((((type w32 pc)) (:inherit (default))) (t (:inherit (font-lock-warning-face)))))
 '(dired-perm-write ((t (:underline (:color foreground-color :style line :position nil) :foreground "#383a42"))))
 '(dired-warning ((t (:foreground "#986801"))))
 '(dired-flagged ((t (:foreground "#e45649"))))
 '(dired-marked ((t (:weight bold :inverse-video t :foreground "#a626a4"))))
 '(dired-mark ((t (:weight bold :foreground "#da8548"))))
 '(dired-header ((t (:weight bold :foreground "#4078f2"))))
 '(ert-test-result-unexpected ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red3"))))
 '(ert-test-result-expected ((((class color) (background light)) (:background "green1")) (((class color) (background dark)) (:background "green3"))))
 '(custom-group-subtitle ((t (:foreground "#e45649"))))
 '(custom-group-tag ((t (:foreground "#b751b6"))))
 '(custom-group-tag-1 ((t (:foreground "#4078f2"))))
 '(custom-face-tag ((t (:inherit (custom-variable-tag)))))
 '(custom-visibility ((t (:foreground "#4078f2"))))
 '(custom-variable-button ((t (:underline (:color foreground-color :style line :position nil) :foreground "#50a14f"))))
 '(custom-variable-tag ((t (:foreground "#a626a4"))))
 '(custom-variable-obsolete ((t (:foreground "#9ca0a4" :background "#fafafa"))))
 '(custom-comment-tag ((t (:foreground "#9ca0a4"))))
 '(custom-comment ((t (:foreground "#383a42" :background "#d8d8d8"))))
 '(custom-link ((t (:inherit (link)))))
 '(custom-state ((t (:foreground "#50a14f" :background "#d8e8d7"))))
 '(custom-documentation ((t nil)))
 '(custom-button-pressed-unraised ((t (:box (:line-width (1 . 1) :color nil :style nil) :foreground "#fafafa" :background "#b751b6"))))
 '(custom-button-pressed ((t (:box (:line-width (1 . 1) :color nil :style nil) :foreground "#fafafa" :background "#4078f2"))))
 '(custom-button-unraised ((t (:box (:line-width (1 . 1) :color nil :style nil) :foreground "#b751b6" :background "#fafafa"))))
 '(custom-button-mouse ((t (:box (:line-width (1 . 1) :color nil :style nil) :foreground "#fafafa" :background "#4078f2"))))
 '(custom-button ((t (:box (:line-width (1 . 1) :color nil :style nil) :foreground "#4078f2" :background "#fafafa"))))
 '(custom-saved ((t (:weight bold :foreground "#50a14f" :background "#d8e8d7"))))
 '(custom-themed ((t (:foreground "#986801" :background "#fafafa"))))
 '(custom-changed ((t (:foreground "#4078f2" :background "#fafafa"))))
 '(custom-set ((t (:foreground "#986801" :background "#fafafa"))))
 '(custom-modified ((t (:foreground "#4078f2" :background "#d4e0f8"))))
 '(custom-rogue ((((class color)) (:background "black" :foreground "pink")) (t (:underline (:color foreground-color :style line :position nil)))))
 '(custom-invalid ((t (:foreground "#e45649" :background "#f5d9d6"))))
 '(widget-button-pressed ((t (:foreground "#e45649"))))
 '(widget-unselected ((t (:inherit (widget-inactive)))))
 '(widget-inactive ((t (:inherit (shadow)))))
 '(widget-single-line-field ((t (:background "#c6c7c7"))))
 '(widget-field ((t (:extend t :box (:line-width (1 . -1) :color "#9ca0a4" :style nil) :background "#c6c7c7"))))
 '(widget-button ((t (:weight bold))))
 '(widget-documentation ((t (:foreground "#50a14f"))))
 '(sgml-namespace ((t (:inherit (font-lock-builtin-face)))))
 '(rectangle-preview ((t (:inherit (region)))))
 '(evil-ex-substitute-replacement ((t (:weight bold :foreground "#50a14f" :background "#f0f0f0"))))
 '(evil-ex-substitute-matches ((t (:weight bold :strike-through t :foreground "#e45649" :background "#f0f0f0"))))
 '(evil-ex-lazy-highlight ((t (:inherit (lazy-highlight)))))
 '(evil-ex-search ((t (:weight normal :foreground "#f0f0f0" :background "#4078f2"))))
 '(evil-ex-info ((t (:slant italic :foreground "#e45649"))))
 '(evil-ex-commands ((nil (:slant italic :underline (:color foreground-color :style line :position nil)))))
 '(edmacro-label ((default (:inherit (bold))) (((class color) (background dark)) (:foreground "light blue")) (((min-colors 88) (class color) (background light)) (:foreground "DarkBlue")) (((class color) (background light)) (:foreground "blue")) (t (:inherit (bold)))))
 '(kmacro-menu-marked ((t (:inherit (warning)))))
 '(kmacro-menu-flagged ((t (:inherit (error)))))
 '(kmacro-menu-mark ((t (:inherit (font-lock-constant-face)))))
 '(icon-button ((((type x w32 ns haiku pgtk) (class color)) (:foreground "black" :background "#808080" :box (:line-width (3 . -1) :color "#404040" :style flat-button) :inherit (icon)))))
 '(icon ((t (:underline nil))))
 '(tooltip ((t (:foreground "#383a42" :background "#e7e7e7"))))
 '(eldoc-highlight-function-argument ((t (:inherit (bold)))))
 '(elisp-shorthand-font-lock-face ((t (:foreground "cyan" :inherit (font-lock-keyword-face)))))
 '(vc-ignored-state ((default (:inherit (vc-state-base)))))
 '(vc-edited-state ((default (:inherit (vc-state-base)))))
 '(vc-missing-state ((default (:inherit (vc-state-base)))))
 '(vc-removed-state ((default (:inherit (vc-state-base)))))
 '(vc-conflict-state ((default (:inherit (vc-state-base)))))
 '(vc-locally-added-state ((default (:inherit (vc-state-base)))))
 '(vc-locked-state ((default (:inherit (vc-state-base)))))
 '(vc-needs-update-state ((default (:inherit (vc-state-base)))))
 '(vc-up-to-date-state ((default (:inherit (vc-state-base)))))
 '(vc-state-base ((default nil)))
 '(elisp-completion-category-definition ((t (:inherit (elisp-completion-category)))))
 '(elisp-completion-category ((t (:inherit (font-lock-type-face)))))
 '(elisp-defcharset ((t (:inherit (elisp-charset)))))
 '(elisp-charset ((t (:inherit (font-lock-type-face)))))
 '(elisp-defcoding ((t (:inherit (elisp-coding)))))
 '(elisp-coding ((t (:inherit (font-lock-type-face)))))
 '(elisp-defoclosure ((t (:inherit (elisp-oclosure)))))
 '(elisp-oclosure ((t (:inherit (font-lock-type-face)))))
 '(elisp-deficon ((t (:inherit (elisp-icon)))))
 '(elisp-icon ((t (:inherit (font-lock-type-face)))))
 '(elisp-defface ((t (:inherit (font-lock-variable-name-face)))))
 '(elisp-defvar ((t (:inherit (font-lock-variable-name-face)))))
 '(elisp-defmacro ((t (:inherit (elisp-defun)))))
 '(elisp-defun ((t (:inherit (font-lock-function-name-face)))))
 '(elisp-constant ((t (:inherit (font-lock-builtin-face)))))
 '(elisp-ampersand ((t (:inherit (font-lock-type-face)))))
 '(elisp-nnoo-backend ((t (:inherit (font-lock-type-face)))))
 '(elisp-group ((t (:inherit (font-lock-type-face)))))
 '(elisp-type ((t (:inherit (font-lock-type-face)))))
 '(elisp-widget-type ((t (:inherit (font-lock-type-face)))))
 '(elisp-slot ((t (:inherit (font-lock-builtin-face)))))
 '(elisp-thing ((t (:inherit (font-lock-type-face)))))
 '(elisp-function-property-declaration ((t (:inherit (font-lock-variable-use-face)))))
 '(elisp-warning-type ((t (:inherit (font-lock-type-face)))))
 '(elisp-variable-at-point ((t (:inherit (bold)))))
 '(elisp-shadowed-variable ((t (:underline (:color foreground-color :style line :position nil) :inherit (elisp-bound-variable)))))
 '(elisp-shadowing-variable ((t (:underline (:color foreground-color :style line :position nil) :inherit (elisp-binding-variable)))))
 '(elisp-bound-variable ((t (:inherit (font-lock-variable-use-face) :foreground reset :slant italic))))
 '(elisp-binding-variable ((t (:inherit (font-lock-variable-name-face) :slant italic))))
 '(elisp-theme ((t (:inherit (font-lock-constant-face)))))
 '(elisp-rx ((((background light)) (:foreground "#00008b")) (((background dark)) (:foreground "#5c9cff"))))
 '(elisp-feature ((t (:inherit (font-lock-constant-face)))))
 '(elisp-throw-tag ((t (:inherit (font-lock-constant-face)))))
 '(elisp-special-form ((t (:inherit (elisp-macro)))))
 '(elisp-macro ((t (:inherit (font-lock-keyword-face)))))
 '(elisp-unknown-call ((default (:inherit (elisp-function))) (((background light)) (:foreground "#2f4f4f")) (((background dark)) (:foreground "#7fa9a9"))))
 '(elisp-non-local-exit ((t (:underline (:color "red" :style line :position nil) :inherit (elisp-function)))))
 '(elisp-function ((t (:inherit (font-lock-function-call-face)))))
 '(elisp-symbol-role-definition ((default (:inherit (font-lock-function-name-face))) (((background light)) (:foreground "#00008b")) (((background dark)) (:foreground "#5c9cff"))))
 '(elisp-symbol-role ((default (:inherit (font-lock-function-call-face))) (((background light)) (:foreground "#00008b")) (((background dark)) (:foreground "#5c9cff"))))
 '(elisp-face ((t (:inherit (font-lock-type-face)))))
 '(elisp-major-mode-name ((((background light)) (:foreground "#006400")) (((background dark)) (:foreground "#4ade80"))))
 '(elisp-condition ((t (:foreground "red"))))
 '(elisp-special-variable-declaration ((t (:inherit (elisp-free-variable)))))
 '(elisp-free-variable ((t (:inherit (font-lock-variable-use-face) :foreground reset :underline (:color foreground-color :style line :position nil)))))
 '(elisp-symbol-at-mouse ((((background light)) (:background "#fff6d8")) (((background dark)) (:background "#00422a"))))
 '(buffer-menu-buffer ((t (:weight bold))))
 '(tabulated-list-fake-header ((t (:weight bold :underline (:color foreground-color :style line :position nil) :overline t))))
 '(match ((t (:weight normal :inherit (ol-match-face)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(tab-bar-tab-highlight ((((class color) (min-colors 88) (background light)) (:foreground "black" :background "grey85" :box (:line-width (1 . 1) :color nil :style released-button))) (((class color) (min-colors 88) (background dark)) (:foreground "white" :background "grey40" :box (:line-width (1 . 1) :color nil :style released-button))) (t (:inverse-video nil))))
 '(tab-bar-tab-ungrouped ((t (:inherit (shadow tab-bar-tab-inactive)))))
 '(tab-bar-tab-group-inactive ((t (:inherit (shadow tab-bar-tab-inactive)))))
 '(tab-bar-tab-group-current ((t (:weight bold :box nil :inherit (tab-bar-tab)))))
 '(tab-bar-tab-inactive ((t (:foreground "#c6c7c7" :background "#f0f0f0"))))
 '(tab-bar-tab ((t (:foreground "#383a42" :background "#fafafa"))))
 '(file-name-shadow ((t (:inherit (shadow)))))
 '(isearch-group-2 ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "#a000a0")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred3")) (t (:inherit (isearch)))))
 '(isearch-group-1 ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "#f000f0")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred1")) (t (:inherit (isearch)))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#ffff5f"))))
 '(isearch-fail ((t (:weight bold :foreground "#f0f0f0" :background "#e45649"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(mouse-drag-and-drop-region ((t (:inherit (region)))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-punctuation-face ((t (:foreground "#3a496e"))))
 '(font-lock-property-use-face ((t (:weight regular :inherit (font-lock-property-name-face)))))
 '(font-lock-property-name-face ((t (:weight bold :foreground "#9f4a46"))))
 '(font-lock-operator-face ((t (:foreground "#4078f2"))))
 '(font-lock-number-face ((t (:foreground "#da8548"))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#4078f2" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#4078f2" :inherit (bold)))))
 '(font-lock-regexp-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-preprocessor-face ((t (:foreground "#4078f2" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:foreground "#4078f2" :inherit (bold)))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(font-lock-constant-face ((t (:foreground "#b751b6"))))
 '(font-lock-type-face ((t (:foreground "#986801"))))
 '(font-lock-variable-use-face ((t (:foreground "#512855" :inherit (font-lock-variable-name-face)))))
 '(font-lock-variable-name-face ((t (:foreground "#6a1868"))))
 '(font-lock-function-call-face ((t (:slant italic :foreground "#852c86" :inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#a626a4"))))
 '(font-lock-builtin-face ((t (:foreground "#a626a4"))))
 '(font-lock-keyword-face ((t (:foreground "#e45649"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#84888b" :inherit (font-lock-comment-face)))))
 '(font-lock-string-face ((t (:foreground "#d78700"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#5f8700"))))
 '(minibuffer-nonselected ((t (:weight bold :foreground "dark red" :background "yellow"))))
 '(completions-common-part ((t (:inherit (ol-match-face)))))
 '(completions-first-difference ((t (:weight normal :inherit (bold)))))
 '(completions-highlight ((t (:inherit (highlight)))))
 '(completions-annotations ((t (:inherit (italic shadow)))))
 '(completions-group-separator ((t (:strike-through t :inherit (shadow)))))
 '(completions-group-title ((t (:slant italic :inherit (shadow)))))
 '(blink-matching-paren-offscreen ((t (:inherit (show-paren-match)))))
 '(separator-line ((((type graphic) (background dark)) (:background "#505050" :height 0.1)) (((type graphic) (background light)) (:background "#a0a0a0" :height 0.1)) (t (:underline (:color foreground-color :style line :position nil) :foreground "ForestGreen"))))
 '(next-error-message ((t (:extend t :inherit (highlight)))))
 '(next-error ((t (:inherit (region)))))
 '(confusingly-reordered ((((supports :underline (:style wave))) (:underline (:color "Red1" :style wave :position nil))) (t (:inherit (warning)))))
 '(help-for-help-header ((t (:height 1.26))))
 '(abbrev-table-name ((t (:inherit (font-lock-function-name-face)))))
 '(button ((t (:inherit (link)))))
 '(show-paren-mismatch ((t (:weight ultra-bold :foreground "#f0f0f0" :background "#e45649"))))
 '(show-paren-match-expression ((t (:inherit (show-paren-match)))))
 '(show-paren-match ((t (:weight bold :foreground "#e45649" :background "#f0f0f0"))))
 '(tty-menu-selected-face ((((class color)) (:background "red")) (t (:inverse-video t))))
 '(tty-menu-disabled-face ((((class color) (min-colors 16)) (:background "blue" :foreground "lightgray")) (((class color)) (:background "blue" :foreground "white")) (t (:inherit (shadow)))))
 '(tty-menu-enabled-face ((((class color)) (:weight bold :background "blue" :foreground "yellow")) (t (:weight bold))))
 '(read-multiple-choice-face ((t (:weight bold :inherit (help-key-binding underline)))))
 '(success ((t (:foreground "#50a14f"))))
 '(warning ((t (:foreground "#986801"))))
 '(error ((t (:foreground "#e45649"))))
 '(glyphless-char ((((type tty)) (:underline (:color foreground-color :style line :position nil) :inherit (escape-glyph))) (((type pc)) (:inherit (escape-glyph))) (t (:height 0.6))))
 '(help-key-binding ((((class color) (min-colors 88) (background light)) (:inherit (fixed-pitch) :box (:line-width (-1 . -1) :color "grey80" :style nil) :foreground "DarkBlue" :background "grey96")) (((class color) (min-colors 88) (background dark)) (:inherit (fixed-pitch) :box (:line-width (-1 . -1) :color "grey35" :style nil) :foreground "LightBlue" :background "grey19")) (((class color grayscale) (background light)) (:inherit (fixed-pitch) :background "grey90")) (((class color grayscale) (background dark)) (:inherit (fixed-pitch) :background "grey25")) (t (:inherit (fixed-pitch) :background "grey90"))))
 '(help-argument-name ((t (:inherit (italic)))))
 '(menu ((((type tty)) (:inverse-video t)) (((type x-toolkit)) nil) (t (:inverse-video t))))
 '(tab-line-inactive ((t (:inherit (tab-line)))))
 '(tab-line-active ((t (:inherit (tab-line)))))
 '(tab-line ((t (:foreground "#f0f0f0" :background "#f0f0f0"))))
 '(tab-bar ((t (:foreground "#f0f0f0" :background "#f0f0f0"))))
 '(tool-bar ((default (:foreground "black" :box (:line-width (1 . 1) :color nil :style released-button))) (((type haiku)) (:background "B_MENU_BACKGROUND_COLOR" :foreground "B_MENU_ITEM_TEXT_COLOR")) (((type x w32 ns pgtk android) (class color)) (:background "grey75")) (((type x) (class mono)) (:background "grey"))))
 '(mouse ((t nil)))
 '(cursor ((t (:background "#4078f2"))))
 '(border ((t nil)))
 '(scroll-bar ((t nil)))
 '(fringe ((t (:foreground "#9ca0a4" :inherit (default)))))
 '(margin ((t (:inherit (default)))))
 '(minibuffer-prompt ((t (:foreground "#4078f2"))))
 '(child-frame-border ((t nil)))
 '(internal-border ((t nil)))
 '(window-divider-last-pixel ((t (:inherit (window-divider)))))
 '(window-divider-first-pixel ((t (:inherit (window-divider)))))
 '(window-divider ((t (:inherit (vertical-border)))))
 '(vertical-border ((t (:foreground "#c8c8c8" :background "#c8c8c8"))))
 '(header-line-inactive ((t (:inherit (header-line)))))
 '(header-line-active ((t (:inherit (header-line)))))
 '(header-line-highlight ((t (:inherit (mode-line-highlight)))))
 '(header-line ((t (:weight bold :background "#e9eded" :inherit (mode-line)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#4078f2"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#a190a7" :background "#e9eded"))))
 '(mode-line-active ((t (:inherit (mode-line)))))
 '(mode-line ((t (:foreground "#383a42" :background "#d7e4e8"))))
 '(nobreak-hyphen ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(nobreak-space ((((class color) (min-colors 88)) (:underline (:color foreground-color :style line :position nil) :inherit (escape-glyph))) (((class color) (min-colors 8)) (:background "magenta")) (t (:inverse-video t))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(escape-glyph ((t (:foreground "#0184bc"))))
 '(fill-column-indicator ((t (:stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :inherit (shadow)))))
 '(line-number-minor-tick ((((class color grayscale) (background light)) (:weight bold :background "grey95")) (((class color grayscale) (background dark)) (:weight bold :background "grey55")) (t (:inherit (line-number)))))
 '(line-number-major-tick ((((class color grayscale) (background light)) (:weight bold :background "grey85")) (((class color grayscale) (background dark)) (:weight bold :background "grey75")) (t (:inherit (line-number)))))
 '(line-number-current-line ((t (:family "Source Code Pro" :weight normal :foreground "#1b2229" :inherit (hl-line default)))))
 '(line-number ((t (:family "Source Code Pro" :weight normal :foreground "#aaaeb1" :inherit (default)))))
 '(trailing-whitespace ((t (:background "#e45649"))))
 '(secondary-selection ((t (:extend t :background "#9ca0a4"))))
 '(region ((t (:extend t :background "#d8d8d8"))))
 '(highlight ((t (:foreground "#f0f0f0" :background "#4078f2"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "#4078f2"))))
 '(shadow ((t (:foreground "#9ca0a4"))))
 '(variable-pitch-text ((t (:height 1.1 :inherit (variable-pitch)))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(fixed-pitch-serif ((t (:family "Monospace Serif"))))
 '(fixed-pitch ((t (:family "Source Code Pro" :height 90))))
 '(underline ((((supports :underline t)) (:underline (:color foreground-color :style line :position nil))) (((supports :weight bold :underline t)) (:weight bold)) (t (:underline (:color foreground-color :style line :position nil)))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(italic ((((supports :slant italic)) (:slant italic)) (((supports :underline t)) (:slant italic :underline (:color foreground-color :style line :position nil))) (t (:slant italic))))
 '(bold ((t (:weight bold))))
 '(default ((t (:family "Source Code Pro" :foundry "ADBO" :width normal :height 90 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#000000" :background "#ffffff" :stipple nil :inherit nil)))))

(provide-theme 'ol)
